apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: master
spec:
  cpu:
    isolated: 2-39,42-79
    reserved: 0-1,40-41
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false 
  nodeSelector:
    node-role.kubernetes.io/master: ""
